#pragma once
#define COMPONENT(...)
#define FUNCTION(...)
#define PROPERTY(...)

#define SYSTEM(...)

#define _TYPE_DATABASE(...)
#define _DATABASE_INIT_FUNC(...)
#define _DATABASE_REGISTER_FUNC(...)

#define MACRO_COMBINE_INNER(A,B) A##B
#define MACRO_COMBINE(A,B) MACRO_COMBINE_INNER(A,B)
#define GENERATED_BODY MACRO_COMBINE(GEN_BODY_,CURRENT_FILE)